### ISSUE TITLE
Introduce a test to create an app for an user

### ISSUE THREAD

**Issue by baudoliver7** [Minlessika/saas#58]
We want to cover creation of an app for an user. You will test :

- Simple creation
- Wrong arguments (empty name for exemple)
- Try to create the same application twice

**Comment by 0pdd** [comment]
@baudoliver7 the puzzle [#67](https://github.com/Minlessika/saas/issues/67) is still not solved.

**Comment by 0pdd** [comment]
@baudoliver7 the puzzle [#72](https://github.com/Minlessika/saas/issues/72) is still not solved; solved: [#67](https://github.com/Minlessika/saas/issues/67).

**Comment by 0pdd** [comment]
@baudoliver7 the puzzle [#75](https://github.com/Minlessika/saas/issues/75) is still not solved; solved: [#67](https://github.com/Minlessika/saas/issues/67), [#72](https://github.com/Minlessika/saas/issues/72).

**Comment by 0pdd** [comment]
@baudoliver7 all 3 puzzles are solved here: [#67](https://github.com/Minlessika/saas/issues/67), [#72](https://github.com/Minlessika/saas/issues/72), [#75](https://github.com/Minlessika/saas/issues/75).
