### ISSUE TITLE
Introduce some tests to create an organization

### ISSUE THREAD

**Issue by baudoliver7** [Minlessika/saas#78]
Take into account theses cases :

- Create a simple organization
- Create an organization with an empty name
- Create an organization with an existing name
- Update a name
- Update a name with existing name

**Comment by 0pdd** [comment]
@baudoliver7 6 puzzles [#80](https://github.com/Minlessika/saas/issues/80), [#81](https://github.com/Minlessika/saas/issues/81), [#82](https://github.com/Minlessika/saas/issues/82), [#83](https://github.com/Minlessika/saas/issues/83), [#84](https://github.com/Minlessika/saas/issues/84), [#85](https://github.com/Minlessika/saas/issues/85) are still not solved.

**Comment by 0pdd** [comment]
@baudoliver7 5 puzzles [#81](https://github.com/Minlessika/saas/issues/81), [#82](https://github.com/Minlessika/saas/issues/82), [#83](https://github.com/Minlessika/saas/issues/83), [#84](https://github.com/Minlessika/saas/issues/84), [#85](https://github.com/Minlessika/saas/issues/85) are still not solved; solved: [#80](https://github.com/Minlessika/saas/issues/80).

**Comment by 0pdd** [comment]
@baudoliver7 4 puzzles [#82](https://github.com/Minlessika/saas/issues/82), [#83](https://github.com/Minlessika/saas/issues/83), [#84](https://github.com/Minlessika/saas/issues/84), [#85](https://github.com/Minlessika/saas/issues/85) are still not solved; solved: [#80](https://github.com/Minlessika/saas/issues/80), [#81](https://github.com/Minlessika/saas/issues/81).

**Comment by 0pdd** [comment]
@baudoliver7 3 puzzles [#83](https://github.com/Minlessika/saas/issues/83), [#84](https://github.com/Minlessika/saas/issues/84), [#85](https://github.com/Minlessika/saas/issues/85) are still not solved; solved: [#80](https://github.com/Minlessika/saas/issues/80), [#81](https://github.com/Minlessika/saas/issues/81), [#82](https://github.com/Minlessika/saas/issues/82).

**Comment by 0pdd** [comment]
@baudoliver7 2 puzzles [#84](https://github.com/Minlessika/saas/issues/84), [#85](https://github.com/Minlessika/saas/issues/85) are still not solved; solved: [#80](https://github.com/Minlessika/saas/issues/80), [#81](https://github.com/Minlessika/saas/issues/81), [#82](https://github.com/Minlessika/saas/issues/82), [#83](https://github.com/Minlessika/saas/issues/83).

**Comment by 0pdd** [comment]
@baudoliver7 the puzzle [#85](https://github.com/Minlessika/saas/issues/85) is still not solved; solved: [#80](https://github.com/Minlessika/saas/issues/80), [#81](https://github.com/Minlessika/saas/issues/81), [#82](https://github.com/Minlessika/saas/issues/82), [#83](https://github.com/Minlessika/saas/issues/83), [#84](https://github.com/Minlessika/saas/issues/84).
