### ISSUE TITLE
Test app setup

### ISSUE THREAD

**Issue by baudoliver7** [Minlessika/saas#92]
We want to app :

- installation
- activation

**Comment by 0pdd** [comment]
@baudoliver7 the puzzle [#98](https://github.com/Minlessika/saas/issues/98) is still not solved.

**Comment by 0pdd** [comment]
@baudoliver7 the puzzle [#100](https://github.com/Minlessika/saas/issues/100) is still not solved; solved: [#98](https://github.com/Minlessika/saas/issues/98).

**Comment by 0pdd** [comment]
@baudoliver7 all 2 puzzles are solved here: [#100](https://github.com/Minlessika/saas/issues/100), [#98](https://github.com/Minlessika/saas/issues/98).
